# Generated by Django 3.2.6 on 2021-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='data',
        ),
        migrations.AlterField(
            model_name='construction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
