# Generated by Django 3.2.6 on 2021-08-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210823_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Construction',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='examcenter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.examcenter'),
            preserve_default=False,
        ),
    ]
